### ISSUE TITLE
小白求教！！！

### ISSUE THREAD

**Issue by raining1123** [flymzero/bearychat_ifttt#1]
大神！
请问我在倍洽里添加了一个incoming机器人，重新名为ifttt，然后在聊天组里输入@ifttt -h之后没有任何反应啊，到底要怎么配置啊？？
已经在IFTTT里开通了Webhooks。

**Comment by flymzero** [comment]
> 大神！
> 请问我在倍洽里添加了一个incoming机器人，重新名为ifttt，然后在聊天组里输入@IFTTT -h之后没有任何反应啊，到底要怎么配置啊？？
> 已经在IFTTT里开通了Webhooks。

这个是robot机器人(互通的)，你那个incoming机器人只能"进"
