### ISSUE TITLE
锲而不舍的小白又来issue了

### ISSUE THREAD

**Issue by raining1123** [flymzero/bearychat_ifttt#2]
![snipaste_2019-01-02_09-55-09](https://user-images.githubusercontent.com/17892238/50578416-d390fb00-0e74-11e9-9d0a-07ecc9161eae.jpg)
想知道通过什么添加机器人。。。直接搜索“ifttt”又搜不到。。。

**Comment by flymzero** [comment]
在bearychat里面机器人分两种，一种是官方已经做好的机器人（这个你能搜索到），另一种是自己自定义的机器人，所以搜索不到。
### 你自定义机器人一般是 ：
- 先确定需要实现机器人的种类 incoming, outgoing, hubot其中一种
- 然后是填写/绑定有些相关参数（api, key....）
- 实现自己的机器人然后部署

至于后面的@某某机器人，或者其他功能，都是看你代码怎么实现功能那块的

**Comment by raining1123** [comment]
我的意思是如何添加您这个IFTTT机器人…

**Comment by flymzero** [comment]
我这个仓库分两个独立服务：
- RTM : 与bearychat通讯
- bcwebhook ：从ifttt发送数据到你服务器再通知到bearchat
具体你可以看下流程图，你可以自己修改相关端口其他的（注意端口防火墙这些东西）。

首先自己有台外网能访问的服务器，需改bcwebhook/main.go中的bcToken，rtm/bc/bc.go中的bcToken（下图），然后把这个仓库代码运行起来
![](https://s2.ax1x.com/2019/01/03/FIbiHH.jpg)

**Comment by flymzero** [comment]
> 我的意思是如何添加您这个IFTTT机器人…

如上

**Comment by raining1123** [comment]
这下懂了！！！十分感谢！请原谅我这个计算机小白~
